### ISSUE TITLE
convert-mention.jsonが見つからず実行に失敗する

### ISSUE THREAD

**Issue by shippokun** [tyankatsu0105/convert-mention-action#22]
# 問題

こちらのactionを利用してメンションを飛ばそうとしたところ下記のログがactionに流れて失敗した
```
Cannot find module '/home/runner/work/repo/repo/.github/convert-mention.json'
```

# 状態の共有
## ディレクトリ階層
```
.github
├── convert-mention.json
└── workflows
    └── github2slack.yml
```

## github2slack.yml
```yml
name: Convert GitHub's mention to Slack's

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request:
    types: [review_requested, created, edited]

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Convert mention
        uses: tyankatsu0105/convert-mention-action@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
```

## convert-mention.json
```json
{
  "github user1": "slack user1",
  "github user2": "slack user2"
}
```

# その他
issueの投げ方雑でごめんなさい🙏
